// * AUTH
export const AUTH_START = "AUTH_START";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_ERROR = "LOGIN_ERROR";
export const SIGNUP_SUCCESS = "SIGNUP_SUCCESS";
export const SIGNUP_ERROR = "SIGNUP_ERROR";
export const SIGNOUT_SUCCESS = "SIGNOUT_SUCCESS";
export const RESENDEMAIL_SUCCESS = "RESENDEMAIL_SUCCESS";
export const ADD_NEW_IMAGE = "ADD_NEW_IMAGE";
export const RECOVERPASSWORD_ERROR = "RECOVERPASSWORD_ERROR";
export const RECOVERPASSWORD_SUCCESS = "RECOVERPASSWORD_SUCCESS";
export const CLEANUP = "CLEANUP";

// * TODOS
export const TODO_START = "TODO_START";
export const NEWTODO_SUCCESS = "NEWTODO_SUCCESS";
export const NEWTODO_ERROR = "NEWTODO_ERROR";

// * PROJECTS
export const PROJECT_START = "PROJECT_START";
export const NEWPROJECT_ERROR = "NEWPROJECT_ERROR";

// * ARCHIVE
export const ARCHIVE_SUCCESS = "ARCHIVE_SUCCESS";

// * SETTINGS
export const CHANGEPROFILE_SUCCESS = "CHANGEPROFILE_SUCCESS";
export const CHANGEPROFILE_ERROR = "CHANGEPROFILE_ERROR";
export const DELETEACCOUNT_SUCCESS = "DELETEACCOUNT_SUCCESS";
export const DELETEACCOUNT_ERROR = "DELETEACCOUNT_ERROR";
